extraEnv: |
  - name: AIRFLOW__API__AUTH_BACKENDS
    value: 'airflow.api.auth.backend.basic_auth'
ags:
  persistence:
    enabled: true
  gitSync:
    enabled: true
    repo: https://github.com/samuele-cozzi/poc-airflow.git
    branch: main
    subPath: dags