apiVersion: batch/v1
kind: Job
metadata:
  name: job2
spec:
  template:
    spec:
      containers:
      - name: job
        image: docker.io/samuelecozzi/job-sample:0.0.2
      restartPolicy: Never
  backoffLimit: 4