apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "jobs.fullname" . }}-pi
  labels:
  {{- include "jobs.labels" . | nindent 4 }}
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - command:
        - perl
        - -Mbignum=bpi
        - -wle
        - print bpi(2000)
        image: perl:5.34.0
        name: pi
      restartPolicy: Never